// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package tmux

import (
	"sync"
)

// Ensure, that ClientMock does implement Client.
// If this is not the case, regenerate this file with moq.
var _ Client = &ClientMock{}

// ClientMock is a mock implementation of Client.
//
//	func TestSomethingThatUsesClient(t *testing.T) {
//
//		// make and configure a mocked Client
//		mockedClient := &ClientMock{
//			AttachSessionFunc: func(session string, window string) error {
//				panic("mock out the AttachSession method")
//			},
//			HasSessionFunc: func(name string) (bool, error) {
//				panic("mock out the HasSession method")
//			},
//			IsInsideTmuxFunc: func() bool {
//				panic("mock out the IsInsideTmux method")
//			},
//			KillSessionFunc: func(name string) error {
//				panic("mock out the KillSession method")
//			},
//			KillWindowFunc: func(session string, window string) error {
//				panic("mock out the KillWindow method")
//			},
//			ListWindowsFunc: func(session string) ([]Window, error) {
//				panic("mock out the ListWindows method")
//			},
//			NewSessionFunc: func(name string, windowName string, dir string, initCmd string) error {
//				panic("mock out the NewSession method")
//			},
//			NewWindowFunc: func(session string, name string, dir string, initCmd string) error {
//				panic("mock out the NewWindow method")
//			},
//			PaneCurrentCommandFunc: func(session string, window string) (string, error) {
//				panic("mock out the PaneCurrentCommand method")
//			},
//			RenameWindowFunc: func(session string, old string, new string) error {
//				panic("mock out the RenameWindow method")
//			},
//			SendKeysFunc: func(session string, window string, keys ...string) error {
//				panic("mock out the SendKeys method")
//			},
//			SwitchClientFunc: func(session string, window string) error {
//				panic("mock out the SwitchClient method")
//			},
//		}
//
//		// use mockedClient in code that requires Client
//		// and then make assertions.
//
//	}
type ClientMock struct {
	// AttachSessionFunc mocks the AttachSession method.
	AttachSessionFunc func(session string, window string) error

	// HasSessionFunc mocks the HasSession method.
	HasSessionFunc func(name string) (bool, error)

	// IsInsideTmuxFunc mocks the IsInsideTmux method.
	IsInsideTmuxFunc func() bool

	// KillSessionFunc mocks the KillSession method.
	KillSessionFunc func(name string) error

	// KillWindowFunc mocks the KillWindow method.
	KillWindowFunc func(session string, window string) error

	// ListWindowsFunc mocks the ListWindows method.
	ListWindowsFunc func(session string) ([]Window, error)

	// NewSessionFunc mocks the NewSession method.
	NewSessionFunc func(name string, windowName string, dir string, initCmd string) error

	// NewWindowFunc mocks the NewWindow method.
	NewWindowFunc func(session string, name string, dir string, initCmd string) error

	// PaneCurrentCommandFunc mocks the PaneCurrentCommand method.
	PaneCurrentCommandFunc func(session string, window string) (string, error)

	// RenameWindowFunc mocks the RenameWindow method.
	RenameWindowFunc func(session string, old string, new string) error

	// SendKeysFunc mocks the SendKeys method.
	SendKeysFunc func(session string, window string, keys ...string) error

	// SwitchClientFunc mocks the SwitchClient method.
	SwitchClientFunc func(session string, window string) error

	// calls tracks calls to the methods.
	calls struct {
		// AttachSession holds details about calls to the AttachSession method.
		AttachSession []struct {
			// Session is the session argument value.
			Session string
			// Window is the window argument value.
			Window string
		}
		// HasSession holds details about calls to the HasSession method.
		HasSession []struct {
			// Name is the name argument value.
			Name string
		}
		// IsInsideTmux holds details about calls to the IsInsideTmux method.
		IsInsideTmux []struct {
		}
		// KillSession holds details about calls to the KillSession method.
		KillSession []struct {
			// Name is the name argument value.
			Name string
		}
		// KillWindow holds details about calls to the KillWindow method.
		KillWindow []struct {
			// Session is the session argument value.
			Session string
			// Window is the window argument value.
			Window string
		}
		// ListWindows holds details about calls to the ListWindows method.
		ListWindows []struct {
			// Session is the session argument value.
			Session string
		}
		// NewSession holds details about calls to the NewSession method.
		NewSession []struct {
			// Name is the name argument value.
			Name string
			// WindowName is the windowName argument value.
			WindowName string
			// Dir is the dir argument value.
			Dir string
			// InitCmd is the initCmd argument value.
			InitCmd string
		}
		// NewWindow holds details about calls to the NewWindow method.
		NewWindow []struct {
			// Session is the session argument value.
			Session string
			// Name is the name argument value.
			Name string
			// Dir is the dir argument value.
			Dir string
			// InitCmd is the initCmd argument value.
			InitCmd string
		}
		// PaneCurrentCommand holds details about calls to the PaneCurrentCommand method.
		PaneCurrentCommand []struct {
			// Session is the session argument value.
			Session string
			// Window is the window argument value.
			Window string
		}
		// RenameWindow holds details about calls to the RenameWindow method.
		RenameWindow []struct {
			// Session is the session argument value.
			Session string
			// Old is the old argument value.
			Old string
			// New is the new argument value.
			New string
		}
		// SendKeys holds details about calls to the SendKeys method.
		SendKeys []struct {
			// Session is the session argument value.
			Session string
			// Window is the window argument value.
			Window string
			// Keys is the keys argument value.
			Keys []string
		}
		// SwitchClient holds details about calls to the SwitchClient method.
		SwitchClient []struct {
			// Session is the session argument value.
			Session string
			// Window is the window argument value.
			Window string
		}
	}
	lockAttachSession      sync.RWMutex
	lockHasSession         sync.RWMutex
	lockIsInsideTmux       sync.RWMutex
	lockKillSession        sync.RWMutex
	lockKillWindow         sync.RWMutex
	lockListWindows        sync.RWMutex
	lockNewSession         sync.RWMutex
	lockNewWindow          sync.RWMutex
	lockPaneCurrentCommand sync.RWMutex
	lockRenameWindow       sync.RWMutex
	lockSendKeys           sync.RWMutex
	lockSwitchClient       sync.RWMutex
}

// AttachSession calls AttachSessionFunc.
func (mock *ClientMock) AttachSession(session string, window string) error {
	if mock.AttachSessionFunc == nil {
		panic("ClientMock.AttachSessionFunc: method is nil but Client.AttachSession was just called")
	}
	callInfo := struct {
		Session string
		Window  string
	}{
		Session: session,
		Window:  window,
	}
	mock.lockAttachSession.Lock()
	mock.calls.AttachSession = append(mock.calls.AttachSession, callInfo)
	mock.lockAttachSession.Unlock()
	return mock.AttachSessionFunc(session, window)
}

// AttachSessionCalls gets all the calls that were made to AttachSession.
// Check the length with:
//
//	len(mockedClient.AttachSessionCalls())
func (mock *ClientMock) AttachSessionCalls() []struct {
	Session string
	Window  string
} {
	var calls []struct {
		Session string
		Window  string
	}
	mock.lockAttachSession.RLock()
	calls = mock.calls.AttachSession
	mock.lockAttachSession.RUnlock()
	return calls
}

// HasSession calls HasSessionFunc.
func (mock *ClientMock) HasSession(name string) (bool, error) {
	if mock.HasSessionFunc == nil {
		panic("ClientMock.HasSessionFunc: method is nil but Client.HasSession was just called")
	}
	callInfo := struct {
		Name string
	}{
		Name: name,
	}
	mock.lockHasSession.Lock()
	mock.calls.HasSession = append(mock.calls.HasSession, callInfo)
	mock.lockHasSession.Unlock()
	return mock.HasSessionFunc(name)
}

// HasSessionCalls gets all the calls that were made to HasSession.
// Check the length with:
//
//	len(mockedClient.HasSessionCalls())
func (mock *ClientMock) HasSessionCalls() []struct {
	Name string
} {
	var calls []struct {
		Name string
	}
	mock.lockHasSession.RLock()
	calls = mock.calls.HasSession
	mock.lockHasSession.RUnlock()
	return calls
}

// IsInsideTmux calls IsInsideTmuxFunc.
func (mock *ClientMock) IsInsideTmux() bool {
	if mock.IsInsideTmuxFunc == nil {
		panic("ClientMock.IsInsideTmuxFunc: method is nil but Client.IsInsideTmux was just called")
	}
	callInfo := struct {
	}{}
	mock.lockIsInsideTmux.Lock()
	mock.calls.IsInsideTmux = append(mock.calls.IsInsideTmux, callInfo)
	mock.lockIsInsideTmux.Unlock()
	return mock.IsInsideTmuxFunc()
}

// IsInsideTmuxCalls gets all the calls that were made to IsInsideTmux.
// Check the length with:
//
//	len(mockedClient.IsInsideTmuxCalls())
func (mock *ClientMock) IsInsideTmuxCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockIsInsideTmux.RLock()
	calls = mock.calls.IsInsideTmux
	mock.lockIsInsideTmux.RUnlock()
	return calls
}

// KillSession calls KillSessionFunc.
func (mock *ClientMock) KillSession(name string) error {
	if mock.KillSessionFunc == nil {
		panic("ClientMock.KillSessionFunc: method is nil but Client.KillSession was just called")
	}
	callInfo := struct {
		Name string
	}{
		Name: name,
	}
	mock.lockKillSession.Lock()
	mock.calls.KillSession = append(mock.calls.KillSession, callInfo)
	mock.lockKillSession.Unlock()
	return mock.KillSessionFunc(name)
}

// KillSessionCalls gets all the calls that were made to KillSession.
// Check the length with:
//
//	len(mockedClient.KillSessionCalls())
func (mock *ClientMock) KillSessionCalls() []struct {
	Name string
} {
	var calls []struct {
		Name string
	}
	mock.lockKillSession.RLock()
	calls = mock.calls.KillSession
	mock.lockKillSession.RUnlock()
	return calls
}

// KillWindow calls KillWindowFunc.
func (mock *ClientMock) KillWindow(session string, window string) error {
	if mock.KillWindowFunc == nil {
		panic("ClientMock.KillWindowFunc: method is nil but Client.KillWindow was just called")
	}
	callInfo := struct {
		Session string
		Window  string
	}{
		Session: session,
		Window:  window,
	}
	mock.lockKillWindow.Lock()
	mock.calls.KillWindow = append(mock.calls.KillWindow, callInfo)
	mock.lockKillWindow.Unlock()
	return mock.KillWindowFunc(session, window)
}

// KillWindowCalls gets all the calls that were made to KillWindow.
// Check the length with:
//
//	len(mockedClient.KillWindowCalls())
func (mock *ClientMock) KillWindowCalls() []struct {
	Session string
	Window  string
} {
	var calls []struct {
		Session string
		Window  string
	}
	mock.lockKillWindow.RLock()
	calls = mock.calls.KillWindow
	mock.lockKillWindow.RUnlock()
	return calls
}

// ListWindows calls ListWindowsFunc.
func (mock *ClientMock) ListWindows(session string) ([]Window, error) {
	if mock.ListWindowsFunc == nil {
		panic("ClientMock.ListWindowsFunc: method is nil but Client.ListWindows was just called")
	}
	callInfo := struct {
		Session string
	}{
		Session: session,
	}
	mock.lockListWindows.Lock()
	mock.calls.ListWindows = append(mock.calls.ListWindows, callInfo)
	mock.lockListWindows.Unlock()
	return mock.ListWindowsFunc(session)
}

// ListWindowsCalls gets all the calls that were made to ListWindows.
// Check the length with:
//
//	len(mockedClient.ListWindowsCalls())
func (mock *ClientMock) ListWindowsCalls() []struct {
	Session string
} {
	var calls []struct {
		Session string
	}
	mock.lockListWindows.RLock()
	calls = mock.calls.ListWindows
	mock.lockListWindows.RUnlock()
	return calls
}

// NewSession calls NewSessionFunc.
func (mock *ClientMock) NewSession(name string, windowName string, dir string, initCmd string) error {
	if mock.NewSessionFunc == nil {
		panic("ClientMock.NewSessionFunc: method is nil but Client.NewSession was just called")
	}
	callInfo := struct {
		Name       string
		WindowName string
		Dir        string
		InitCmd    string
	}{
		Name:       name,
		WindowName: windowName,
		Dir:        dir,
		InitCmd:    initCmd,
	}
	mock.lockNewSession.Lock()
	mock.calls.NewSession = append(mock.calls.NewSession, callInfo)
	mock.lockNewSession.Unlock()
	return mock.NewSessionFunc(name, windowName, dir, initCmd)
}

// NewSessionCalls gets all the calls that were made to NewSession.
// Check the length with:
//
//	len(mockedClient.NewSessionCalls())
func (mock *ClientMock) NewSessionCalls() []struct {
	Name       string
	WindowName string
	Dir        string
	InitCmd    string
} {
	var calls []struct {
		Name       string
		WindowName string
		Dir        string
		InitCmd    string
	}
	mock.lockNewSession.RLock()
	calls = mock.calls.NewSession
	mock.lockNewSession.RUnlock()
	return calls
}

// NewWindow calls NewWindowFunc.
func (mock *ClientMock) NewWindow(session string, name string, dir string, initCmd string) error {
	if mock.NewWindowFunc == nil {
		panic("ClientMock.NewWindowFunc: method is nil but Client.NewWindow was just called")
	}
	callInfo := struct {
		Session string
		Name    string
		Dir     string
		InitCmd string
	}{
		Session: session,
		Name:    name,
		Dir:     dir,
		InitCmd: initCmd,
	}
	mock.lockNewWindow.Lock()
	mock.calls.NewWindow = append(mock.calls.NewWindow, callInfo)
	mock.lockNewWindow.Unlock()
	return mock.NewWindowFunc(session, name, dir, initCmd)
}

// NewWindowCalls gets all the calls that were made to NewWindow.
// Check the length with:
//
//	len(mockedClient.NewWindowCalls())
func (mock *ClientMock) NewWindowCalls() []struct {
	Session string
	Name    string
	Dir     string
	InitCmd string
} {
	var calls []struct {
		Session string
		Name    string
		Dir     string
		InitCmd string
	}
	mock.lockNewWindow.RLock()
	calls = mock.calls.NewWindow
	mock.lockNewWindow.RUnlock()
	return calls
}

// PaneCurrentCommand calls PaneCurrentCommandFunc.
func (mock *ClientMock) PaneCurrentCommand(session string, window string) (string, error) {
	if mock.PaneCurrentCommandFunc == nil {
		panic("ClientMock.PaneCurrentCommandFunc: method is nil but Client.PaneCurrentCommand was just called")
	}
	callInfo := struct {
		Session string
		Window  string
	}{
		Session: session,
		Window:  window,
	}
	mock.lockPaneCurrentCommand.Lock()
	mock.calls.PaneCurrentCommand = append(mock.calls.PaneCurrentCommand, callInfo)
	mock.lockPaneCurrentCommand.Unlock()
	return mock.PaneCurrentCommandFunc(session, window)
}

// PaneCurrentCommandCalls gets all the calls that were made to PaneCurrentCommand.
// Check the length with:
//
//	len(mockedClient.PaneCurrentCommandCalls())
func (mock *ClientMock) PaneCurrentCommandCalls() []struct {
	Session string
	Window  string
} {
	var calls []struct {
		Session string
		Window  string
	}
	mock.lockPaneCurrentCommand.RLock()
	calls = mock.calls.PaneCurrentCommand
	mock.lockPaneCurrentCommand.RUnlock()
	return calls
}

// RenameWindow calls RenameWindowFunc.
func (mock *ClientMock) RenameWindow(session string, old string, new string) error {
	if mock.RenameWindowFunc == nil {
		panic("ClientMock.RenameWindowFunc: method is nil but Client.RenameWindow was just called")
	}
	callInfo := struct {
		Session string
		Old     string
		New     string
	}{
		Session: session,
		Old:     old,
		New:     new,
	}
	mock.lockRenameWindow.Lock()
	mock.calls.RenameWindow = append(mock.calls.RenameWindow, callInfo)
	mock.lockRenameWindow.Unlock()
	return mock.RenameWindowFunc(session, old, new)
}

// RenameWindowCalls gets all the calls that were made to RenameWindow.
// Check the length with:
//
//	len(mockedClient.RenameWindowCalls())
func (mock *ClientMock) RenameWindowCalls() []struct {
	Session string
	Old     string
	New     string
} {
	var calls []struct {
		Session string
		Old     string
		New     string
	}
	mock.lockRenameWindow.RLock()
	calls = mock.calls.RenameWindow
	mock.lockRenameWindow.RUnlock()
	return calls
}

// SendKeys calls SendKeysFunc.
func (mock *ClientMock) SendKeys(session string, window string, keys ...string) error {
	if mock.SendKeysFunc == nil {
		panic("ClientMock.SendKeysFunc: method is nil but Client.SendKeys was just called")
	}
	callInfo := struct {
		Session string
		Window  string
		Keys    []string
	}{
		Session: session,
		Window:  window,
		Keys:    keys,
	}
	mock.lockSendKeys.Lock()
	mock.calls.SendKeys = append(mock.calls.SendKeys, callInfo)
	mock.lockSendKeys.Unlock()
	return mock.SendKeysFunc(session, window, keys...)
}

// SendKeysCalls gets all the calls that were made to SendKeys.
// Check the length with:
//
//	len(mockedClient.SendKeysCalls())
func (mock *ClientMock) SendKeysCalls() []struct {
	Session string
	Window  string
	Keys    []string
} {
	var calls []struct {
		Session string
		Window  string
		Keys    []string
	}
	mock.lockSendKeys.RLock()
	calls = mock.calls.SendKeys
	mock.lockSendKeys.RUnlock()
	return calls
}

// SwitchClient calls SwitchClientFunc.
func (mock *ClientMock) SwitchClient(session string, window string) error {
	if mock.SwitchClientFunc == nil {
		panic("ClientMock.SwitchClientFunc: method is nil but Client.SwitchClient was just called")
	}
	callInfo := struct {
		Session string
		Window  string
	}{
		Session: session,
		Window:  window,
	}
	mock.lockSwitchClient.Lock()
	mock.calls.SwitchClient = append(mock.calls.SwitchClient, callInfo)
	mock.lockSwitchClient.Unlock()
	return mock.SwitchClientFunc(session, window)
}

// SwitchClientCalls gets all the calls that were made to SwitchClient.
// Check the length with:
//
//	len(mockedClient.SwitchClientCalls())
func (mock *ClientMock) SwitchClientCalls() []struct {
	Session string
	Window  string
} {
	var calls []struct {
		Session string
		Window  string
	}
	mock.lockSwitchClient.RLock()
	calls = mock.calls.SwitchClient
	mock.lockSwitchClient.RUnlock()
	return calls
}
