version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/wasabi0522/hashi/cmd.version={{.Version}}

homebrew_casks:
  - repository:
      owner: wasabi0522
      name: homebrew-tap
    homepage: https://github.com/wasabi0522/hashi
    description: Git worktree + tmux session manager
    license: MIT
    binaries:
      - hashi
    url:
      verified: github.com/wasabi0522/hashi
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hashi"]
          end

archives:
  - formats: ['tar.gz']
    name_template: >-
      {{ .ProjectName }}_{{ .Os }}_{{ .Arch }}
