// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package exec

import (
	"context"
	"sync"
)

// Ensure, that ExecutorMock does implement Executor.
// If this is not the case, regenerate this file with moq.
var _ Executor = &ExecutorMock{}

// ExecutorMock is a mock implementation of Executor.
//
//	func TestSomethingThatUsesExecutor(t *testing.T) {
//
//		// make and configure a mocked Executor
//		mockedExecutor := &ExecutorMock{
//			LookPathFunc: func(name string) error {
//				panic("mock out the LookPath method")
//			},
//			OutputFunc: func(name string, args ...string) (string, error) {
//				panic("mock out the Output method")
//			},
//			RunFunc: func(name string, args ...string) error {
//				panic("mock out the Run method")
//			},
//			RunInteractiveFunc: func(name string, args ...string) error {
//				panic("mock out the RunInteractive method")
//			},
//			RunShellFunc: func(command string, dir string) error {
//				panic("mock out the RunShell method")
//			},
//			RunShellContextFunc: func(ctx context.Context, command string, dir string) error {
//				panic("mock out the RunShellContext method")
//			},
//		}
//
//		// use mockedExecutor in code that requires Executor
//		// and then make assertions.
//
//	}
type ExecutorMock struct {
	// LookPathFunc mocks the LookPath method.
	LookPathFunc func(name string) error

	// OutputFunc mocks the Output method.
	OutputFunc func(name string, args ...string) (string, error)

	// RunFunc mocks the Run method.
	RunFunc func(name string, args ...string) error

	// RunInteractiveFunc mocks the RunInteractive method.
	RunInteractiveFunc func(name string, args ...string) error

	// RunShellFunc mocks the RunShell method.
	RunShellFunc func(command string, dir string) error

	// RunShellContextFunc mocks the RunShellContext method.
	RunShellContextFunc func(ctx context.Context, command string, dir string) error

	// calls tracks calls to the methods.
	calls struct {
		// LookPath holds details about calls to the LookPath method.
		LookPath []struct {
			// Name is the name argument value.
			Name string
		}
		// Output holds details about calls to the Output method.
		Output []struct {
			// Name is the name argument value.
			Name string
			// Args is the args argument value.
			Args []string
		}
		// Run holds details about calls to the Run method.
		Run []struct {
			// Name is the name argument value.
			Name string
			// Args is the args argument value.
			Args []string
		}
		// RunInteractive holds details about calls to the RunInteractive method.
		RunInteractive []struct {
			// Name is the name argument value.
			Name string
			// Args is the args argument value.
			Args []string
		}
		// RunShell holds details about calls to the RunShell method.
		RunShell []struct {
			// Command is the command argument value.
			Command string
			// Dir is the dir argument value.
			Dir string
		}
		// RunShellContext holds details about calls to the RunShellContext method.
		RunShellContext []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Command is the command argument value.
			Command string
			// Dir is the dir argument value.
			Dir string
		}
	}
	lockLookPath        sync.RWMutex
	lockOutput          sync.RWMutex
	lockRun             sync.RWMutex
	lockRunInteractive  sync.RWMutex
	lockRunShell        sync.RWMutex
	lockRunShellContext sync.RWMutex
}

// LookPath calls LookPathFunc.
func (mock *ExecutorMock) LookPath(name string) error {
	if mock.LookPathFunc == nil {
		panic("ExecutorMock.LookPathFunc: method is nil but Executor.LookPath was just called")
	}
	callInfo := struct {
		Name string
	}{
		Name: name,
	}
	mock.lockLookPath.Lock()
	mock.calls.LookPath = append(mock.calls.LookPath, callInfo)
	mock.lockLookPath.Unlock()
	return mock.LookPathFunc(name)
}

// LookPathCalls gets all the calls that were made to LookPath.
// Check the length with:
//
//	len(mockedExecutor.LookPathCalls())
func (mock *ExecutorMock) LookPathCalls() []struct {
	Name string
} {
	var calls []struct {
		Name string
	}
	mock.lockLookPath.RLock()
	calls = mock.calls.LookPath
	mock.lockLookPath.RUnlock()
	return calls
}

// Output calls OutputFunc.
func (mock *ExecutorMock) Output(name string, args ...string) (string, error) {
	if mock.OutputFunc == nil {
		panic("ExecutorMock.OutputFunc: method is nil but Executor.Output was just called")
	}
	callInfo := struct {
		Name string
		Args []string
	}{
		Name: name,
		Args: args,
	}
	mock.lockOutput.Lock()
	mock.calls.Output = append(mock.calls.Output, callInfo)
	mock.lockOutput.Unlock()
	return mock.OutputFunc(name, args...)
}

// OutputCalls gets all the calls that were made to Output.
// Check the length with:
//
//	len(mockedExecutor.OutputCalls())
func (mock *ExecutorMock) OutputCalls() []struct {
	Name string
	Args []string
} {
	var calls []struct {
		Name string
		Args []string
	}
	mock.lockOutput.RLock()
	calls = mock.calls.Output
	mock.lockOutput.RUnlock()
	return calls
}

// Run calls RunFunc.
func (mock *ExecutorMock) Run(name string, args ...string) error {
	if mock.RunFunc == nil {
		panic("ExecutorMock.RunFunc: method is nil but Executor.Run was just called")
	}
	callInfo := struct {
		Name string
		Args []string
	}{
		Name: name,
		Args: args,
	}
	mock.lockRun.Lock()
	mock.calls.Run = append(mock.calls.Run, callInfo)
	mock.lockRun.Unlock()
	return mock.RunFunc(name, args...)
}

// RunCalls gets all the calls that were made to Run.
// Check the length with:
//
//	len(mockedExecutor.RunCalls())
func (mock *ExecutorMock) RunCalls() []struct {
	Name string
	Args []string
} {
	var calls []struct {
		Name string
		Args []string
	}
	mock.lockRun.RLock()
	calls = mock.calls.Run
	mock.lockRun.RUnlock()
	return calls
}

// RunInteractive calls RunInteractiveFunc.
func (mock *ExecutorMock) RunInteractive(name string, args ...string) error {
	if mock.RunInteractiveFunc == nil {
		panic("ExecutorMock.RunInteractiveFunc: method is nil but Executor.RunInteractive was just called")
	}
	callInfo := struct {
		Name string
		Args []string
	}{
		Name: name,
		Args: args,
	}
	mock.lockRunInteractive.Lock()
	mock.calls.RunInteractive = append(mock.calls.RunInteractive, callInfo)
	mock.lockRunInteractive.Unlock()
	return mock.RunInteractiveFunc(name, args...)
}

// RunInteractiveCalls gets all the calls that were made to RunInteractive.
// Check the length with:
//
//	len(mockedExecutor.RunInteractiveCalls())
func (mock *ExecutorMock) RunInteractiveCalls() []struct {
	Name string
	Args []string
} {
	var calls []struct {
		Name string
		Args []string
	}
	mock.lockRunInteractive.RLock()
	calls = mock.calls.RunInteractive
	mock.lockRunInteractive.RUnlock()
	return calls
}

// RunShell calls RunShellFunc.
func (mock *ExecutorMock) RunShell(command string, dir string) error {
	if mock.RunShellFunc == nil {
		panic("ExecutorMock.RunShellFunc: method is nil but Executor.RunShell was just called")
	}
	callInfo := struct {
		Command string
		Dir     string
	}{
		Command: command,
		Dir:     dir,
	}
	mock.lockRunShell.Lock()
	mock.calls.RunShell = append(mock.calls.RunShell, callInfo)
	mock.lockRunShell.Unlock()
	return mock.RunShellFunc(command, dir)
}

// RunShellCalls gets all the calls that were made to RunShell.
// Check the length with:
//
//	len(mockedExecutor.RunShellCalls())
func (mock *ExecutorMock) RunShellCalls() []struct {
	Command string
	Dir     string
} {
	var calls []struct {
		Command string
		Dir     string
	}
	mock.lockRunShell.RLock()
	calls = mock.calls.RunShell
	mock.lockRunShell.RUnlock()
	return calls
}

// RunShellContext calls RunShellContextFunc.
func (mock *ExecutorMock) RunShellContext(ctx context.Context, command string, dir string) error {
	if mock.RunShellContextFunc == nil {
		panic("ExecutorMock.RunShellContextFunc: method is nil but Executor.RunShellContext was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Command string
		Dir     string
	}{
		Ctx:     ctx,
		Command: command,
		Dir:     dir,
	}
	mock.lockRunShellContext.Lock()
	mock.calls.RunShellContext = append(mock.calls.RunShellContext, callInfo)
	mock.lockRunShellContext.Unlock()
	return mock.RunShellContextFunc(ctx, command, dir)
}

// RunShellContextCalls gets all the calls that were made to RunShellContext.
// Check the length with:
//
//	len(mockedExecutor.RunShellContextCalls())
func (mock *ExecutorMock) RunShellContextCalls() []struct {
	Ctx     context.Context
	Command string
	Dir     string
} {
	var calls []struct {
		Ctx     context.Context
		Command string
		Dir     string
	}
	mock.lockRunShellContext.RLock()
	calls = mock.calls.RunShellContext
	mock.lockRunShellContext.RUnlock()
	return calls
}
